'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class PubRes
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WordTrans.PubRes", GetType(PubRes).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  使用此强类型资源类，为所有资源查找
        '''  重写当前线程的 CurrentUICulture 属性。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property defaultSettings() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("defaultSettings", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property ImageC2E() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageC2E", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property ImageE2C() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageE2C", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property ImageMore() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageMore", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property ImageSettings() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageSettings", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property ImageSign() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageSign", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 \settings.json 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property StringSettingPath() As String
            Get
                Return ResourceManager.GetString("StringSettingPath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 http://api.fanyi.baidu.com/api/trans/product/index 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property StringSignURL() As String
            Get
                Return ResourceManager.GetString("StringSignURL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 http://api.fanyi.baidu.com/api/trans/vip/translate 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property StringTransURL() As String
            Get
                Return ResourceManager.GetString("StringTransURL", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
